/*
 *
 */

package com.routineguard.gui;

import com.routineguard.core.*;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JFrame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Alexandre
 */
public class DisplayInterface extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form DisplaytInterface
     */
    public DisplayInterface(Routine _routine) {
        this.routineInUse = _routine;
        this.setTitle("RoutineGuard");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        displayHour();
        displayRoutineInit();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        menu = new javax.swing.JDialog();
        setRoutineButton = new javax.swing.JButton();
        rebootButton = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        setRoutineDialog = new javax.swing.JDialog();
        beginHourLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        comboBeginHour = new javax.swing.JComboBox<String>();
        jLabel10 = new javax.swing.JLabel();
        comboBeginMin = new javax.swing.JComboBox<String>();
        jLabel11 = new javax.swing.JLabel();
        comboDurationHour = new javax.swing.JComboBox<String>();
        jLabel14 = new javax.swing.JLabel();
        comboDurationMin = new javax.swing.JComboBox<String>();
        jLabel15 = new javax.swing.JLabel();
        comboTolerance = new javax.swing.JComboBox<String>();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        comboEventType = new javax.swing.JComboBox<String>();
        textFieldDescription = new javax.swing.JTextField();
        textFieldImportance = new javax.swing.JTextField();
        validEventButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        addVisitButton = new javax.swing.JButton();
        addOutingButton = new javax.swing.JButton();
        date_Label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setRoutineButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        setRoutineButton.setText("Configurez la routine");
        setRoutineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setRoutineButtonActionPerformed(evt);
            }
        });

        rebootButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rebootButton.setText("Redémarrer");
        rebootButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rebootButtonActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setText("Arrêter");

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu.getContentPane());
        menu.getContentPane().setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rebootButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(setRoutineButton, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addComponent(setRoutineButton, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rebootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton3.setText("Arrêter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setRoutineDialog.setMaximumSize(new java.awt.Dimension(900, 500));
        setRoutineDialog.setMinimumSize(new java.awt.Dimension(800, 430));
        setRoutineDialog.setSize(new java.awt.Dimension(800, 430));
        setRoutineDialog.getContentPane().setLayout(new java.awt.GridBagLayout());

        beginHourLabel.setText("beginHour : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        setRoutineDialog.getContentPane().add(beginHourLabel, gridBagConstraints);

        jLabel4.setText("duration : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        setRoutineDialog.getContentPane().add(jLabel4, gridBagConstraints);

        jLabel5.setText("tolerance");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        setRoutineDialog.getContentPane().add(jLabel5, gridBagConstraints);

        jLabel7.setText("eventType : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        setRoutineDialog.getContentPane().add(jLabel7, gridBagConstraints);

        jLabel8.setText("eventDescription : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        setRoutineDialog.getContentPane().add(jLabel8, gridBagConstraints);

        jLabel9.setText("eventImportance : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        setRoutineDialog.getContentPane().add(jLabel9, gridBagConstraints);

        comboBeginHour.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        setRoutineDialog.getContentPane().add(comboBeginHour, gridBagConstraints);

        jLabel10.setText("  H  ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        setRoutineDialog.getContentPane().add(jLabel10, gridBagConstraints);

        comboBeginMin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "10", "20", "30", "40", "50" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        setRoutineDialog.getContentPane().add(comboBeginMin, gridBagConstraints);

        jLabel11.setText("  Min");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        setRoutineDialog.getContentPane().add(jLabel11, gridBagConstraints);

        comboDurationHour.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        setRoutineDialog.getContentPane().add(comboDurationHour, gridBagConstraints);

        jLabel14.setText("  H  ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        setRoutineDialog.getContentPane().add(jLabel14, gridBagConstraints);

        comboDurationMin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "10", "20", "30", "40", "50" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        setRoutineDialog.getContentPane().add(comboDurationMin, gridBagConstraints);

        jLabel15.setText("  Min");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        setRoutineDialog.getContentPane().add(jLabel15, gridBagConstraints);

        comboTolerance.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        setRoutineDialog.getContentPane().add(comboTolerance, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        setRoutineDialog.getContentPane().add(jLabel19, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        setRoutineDialog.getContentPane().add(jLabel21, gridBagConstraints);

        comboEventType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OUTING", "VISIT", "BREAKFAST", "LUNCH", "DINNER", "OTHER_MEAL", "AWAKENING", "SLEEPING", "NONE" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        setRoutineDialog.getContentPane().add(comboEventType, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        setRoutineDialog.getContentPane().add(textFieldDescription, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        setRoutineDialog.getContentPane().add(textFieldImportance, gridBagConstraints);

        validEventButton.setText("Valider");
        validEventButton.setToolTipText("");
        validEventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validEventButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        setRoutineDialog.getContentPane().add(validEventButton, gridBagConstraints);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setRoutineDialog.getContentPane().add(jPanel2, new java.awt.GridBagConstraints());

        int a = 0;

        jButton7.setText("jButton7");

        jButton8.setText("jButton8");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/routineguard/gui/telephone.png"))); // NOI18N
        jButton1.setText(" Téléassistance");
        jButton1.setActionCommand("jButton2");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        addVisitButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addVisitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/routineguard/gui/Sortie2.png"))); // NOI18N
        addVisitButton.setText("Visite          ");
        addVisitButton.setActionCommand("jButton2");
        addVisitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVisitButtonActionPerformed(evt);
            }
        });

        addOutingButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addOutingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/routineguard/gui/Sortie.png"))); // NOI18N
        addOutingButton.setText("  Sortie            ");
        addOutingButton.setActionCommand("jButton3");
        addOutingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOutingButtonActionPerformed(evt);
            }
        });

        date_Label.setBackground(new java.awt.Color(255, 255, 255));
        date_Label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        date_Label.setText("Lundi 46 avril :     12h30");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/routineguard/gui/RoutineGuard_BLUE.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 100));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setForeground(new java.awt.Color(153, 0, 153));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/routineguard/gui/Reglage.PNG"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(date_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addVisitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(addOutingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(addVisitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(addOutingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(date_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addVisitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVisitButtonActionPerformed
        // TODO add your handling code here:
        Boolean test = true;
        AddVisite visite = new AddVisite(this, test, EventType.VISIT);
        visite.setVisible(true);
    }//GEN-LAST:event_addVisitButtonActionPerformed

    private void addOutingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOutingButtonActionPerformed
        // TODO add your handling code here:
        Boolean test = true;
        AddVisite visite = new AddVisite(this, test, EventType.OUTING);
        visite.setVisible(true);
    }//GEN-LAST:event_addOutingButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    private void rebootButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rebootButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rebootButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        menu.setVisible(true);
        menu.pack();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void setRoutineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setRoutineButtonActionPerformed
        // TODO add your handling code here:
        menu.setVisible(false);
        displayRoutineInit();
    }//GEN-LAST:event_setRoutineButtonActionPerformed

    private void validEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validEventButtonActionPerformed
        // TODO add your handling code here:
        int beginHour = Integer.parseInt("" + comboBeginHour.getSelectedItem());
        int timeSlot = Integer.parseInt("" + comboBeginMin.getSelectedItem()) / 10;
        int duration = (Integer.parseInt("" + comboDurationHour.getSelectedItem()))
                *60 + (Integer.parseInt("" + comboDurationMin.getSelectedItem()));
        int tolerance = Integer.parseInt("" + comboTolerance.getSelectedItem());
        String strEventType = "" + comboEventType.getSelectedItem();
        
        EventType eventType = EventType.NONE;
        switch (strEventType){
            case "OUTING":{
                eventType = EventType.OUTING;
                break;
            }
            case "VISIT":{
                eventType = EventType.VISIT;
                break;
            }
            case "BREAKFAST":{
                eventType = EventType.BREAKFAST;
                break;
            }
            case "LUNCH":{
                eventType = EventType.LUNCH;
                break;
            }
            case "DINNER":{
                eventType = EventType.DINNER;
                break;
            }
            case "OTHER_MEAL":{
                eventType = EventType.OTHER_MEAL;
                break;
            }
            case "AWAKENING":{
                eventType = EventType.AWAKENING;
                break;
            }
            case "SLEEPING":{
                eventType = EventType.SLEEPING;
                break;
            }
            case "NONE":{
                eventType = EventType.NONE;
                break;
            }  
        }
        String description = textFieldDescription.getText();
        int importance = Integer.parseInt(textFieldImportance.getText());
        
        Event event = new Event(beginHour, timeSlot, duration, tolerance, eventType, importance, description);
        routineInUse.addEvent(event);
        setRoutineDialog.setVisible(false);
        displayRoutineInit();

    }//GEN-LAST:event_validEventButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new DisplayInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOutingButton;
    private javax.swing.JButton addVisitButton;
    private javax.swing.JLabel beginHourLabel;
    private javax.swing.JComboBox<String> comboBeginHour;
    private javax.swing.JComboBox<String> comboBeginMin;
    private javax.swing.JComboBox<String> comboDurationHour;
    private javax.swing.JComboBox<String> comboDurationMin;
    private javax.swing.JComboBox<String> comboEventType;
    private javax.swing.JComboBox<String> comboTolerance;
    private javax.swing.JLabel date_Label;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JDialog menu;
    private javax.swing.JButton rebootButton;
    private javax.swing.JButton setRoutineButton;
    private javax.swing.JDialog setRoutineDialog;
    private javax.swing.JTextField textFieldDescription;
    private javax.swing.JTextField textFieldImportance;
    private javax.swing.JButton validEventButton;
    // End of variables declaration//GEN-END:variables
    private JPanel pano;
    private GridBagConstraints constr;
    Routine routineInUse;
    private ArrayList <JLabel> listLabel;
    private JButton addEvent;
    private JFrame displayRoutine;
    private JButton deleteEvent;
    
    public void displayRoutineInit(){
        String tempLabel;
        listLabel = new ArrayList();
        displayRoutine = new JFrame();
        pano = new JPanel();
        pano.setLayout(new GridBagLayout());
        constr = new GridBagConstraints();
        constr.fill=GridBagConstraints.HORIZONTAL;
        displayRoutine.add(pano);
        int tempDuration;
        int tempStartHour;
        int tempStartMin;
        int tempEndHour;
        int tempEndMin;

        for (int i = 0; i < routineInUse.getRoutine().size(); i++){
            
            tempStartHour = routineInUse.getRoutine().get(i).getBeginHour();
            tempStartMin = routineInUse.getRoutine().get(i).getTimeSlot()*10;
            tempDuration = routineInUse.getRoutine().get(i).getDuration();
            tempEndHour = tempStartHour + tempDuration / 60;
            tempEndMin = tempStartMin + tempDuration % 60;
            
            if (tempEndMin > 59){
                tempEndHour ++;
                tempEndMin -= 60;
            }
            
            tempLabel = "Event " +  i + " | " + routineInUse.getRoutine().get(i).getStringEventType() + " de " + tempStartHour + "h " + tempStartMin + " à " + tempEndHour + "h " + tempEndMin + "    ";
            
            listLabel.add(new JLabel(tempLabel));
            constr.gridx = 0;
            constr.gridy = i;
            pano.add(listLabel.get(i), constr);
        }
        constr.gridy = routineInUse.getRoutine().size() + 1;
        addEvent = new JButton("Ajouter un événement");
        addEvent.addActionListener(this);
        deleteEvent = new JButton("Supprimer un événement");
        constr.gridy = routineInUse.getRoutine().size() + 2;
        pano.add(deleteEvent);
        pano.add(addEvent);
        displayRoutine.pack();
        displayRoutine.setVisible(true);
    }
    
    public void displayHour(){

        String txtDate=new SimpleDateFormat("EEEEEEEE, d MMM yyyy HH:mm:ss", Locale.FRANCE).format(new Date());
        date_Label.setText(txtDate);      
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == addEvent){
            displayRoutine.setVisible(false);
            setRoutineDialog.setVisible(true);
        }
    }
}